name: any_screen
description: "A flutter package that simplifies the process of building responsive UIs"
version: 0.1.1
repository: https://github.com/athulacaj/any_screen
homepage:

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
